platform:ios,'8.0'
#
source 'https://github.com/CocoaPods/Specs.git'
plugin 'cocoapods-repo-svn', :sources => [
]


target 'AIFMapLib'do
pod 'MJExtension', '3.2.1'
pod 'LazyScroll', '1.0.1'
pod 'YTKKeyValueStore', '0.1.2'

pod  'AMap3DMap-NO-IDFA' , '7.1.0'
pod  'AMapSearch-NO-IDFA', '7.1.0'
pod  'AMapLocation-NO-IDFA', '2.6.3'
pod  'Masonry'

end

inhibit_all_warnings!
